# Generated by Django 3.2.8 on 2021-10-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=1)),
                ('value', models.DecimalField(decimal_places=1, max_digits=4)),
                ('qty', models.IntegerField()),
            ],
        ),
    ]
