# Generated by Django 3.2.8 on 2021-10-16 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='roduct',
        ),
    ]
