# Generated by Django 3.2.8 on 2021-10-16 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_product_roduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='roduct',
            new_name='Product',
        ),
    ]
