# Generated by Django 3.2.8 on 2021-10-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_roduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('A', 'Type A'), ('B', 'Type B'), ('C', 'Type C')], max_length=1),
        ),
    ]
