# Generated by Django 3.2.8 on 2021-10-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='products',
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(to='sales.Product'),
        ),
    ]
