# Generated by Django 3.2.8 on 2021-10-16 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20211016_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='productqty',
            name='sale',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sales.sale'),
            preserve_default=False,
        ),
    ]
