# Generated by Django 3.2.8 on 2021-10-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_productqty_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productqty',
            name='sale',
        ),
    ]
