# Generated by Django 3.2.8 on 2021-10-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_productqty_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='products',
        ),
    ]
