# Generated by Django 3.2.8 on 2021-10-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_remove_sale_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productqty',
            name='sale',
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(to='sales.ProductQty'),
        ),
    ]
