# Generated by Django 3.2.8 on 2021-10-17 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_auto_20211017_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
    ]
