# Generated by Django 3.2.8 on 2021-10-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_auto_20211017_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashback',
            name='sold_at',
            field=models.DateTimeField(),
        ),
    ]
