# Generated by Django 3.2.8 on 2021-10-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_alter_cashback_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashback',
            name='products',
            field=models.ManyToManyField(blank=True, to='sales.Product'),
        ),
    ]
