# Generated by Django 3.2.8 on 2021-10-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_alter_cashback_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='cashback',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
